@type {import('tailwindcss').Config}
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "error": "#ba1a1a",
                "secondary-fixed-dim": "#afc9ea",
                "error-container": "#ffdad6",
                "tertiary-fixed-dim": "#e9c176",
                "primary-fixed-dim": "#bac8dc",
                "on-secondary-container": "#48617e",
                "on-primary-fixed": "#0f1c2c",
                "on-tertiary-container": "#b6924c",
                "outline-variant": "#c6c5d4",
                "on-tertiary-fixed-variant": "#5d4201",
                "surface-bright": "#f9faf5",
                "tertiary-fixed": "#ffdea5",
                "on-primary-fixed-variant": "#3a4859",
                "surface-dim": "#d9dad6",
                "surface-container-highest": "#e2e3df",
                "primary-container": "#233141",
                "tertiary": "#251800",
                "on-primary-container": "#8b99ac",
                "background": "#f9faf5",
                "on-error": "#ffffff",
                "on-primary": "#ffffff",
                "on-secondary": "#ffffff",
                "secondary": "#47607e",
                "secondary-container": "#c2dcff",
                "on-secondary-fixed": "#001d36",
                "inverse-primary": "#bac8dc",
                "surface-variant": "#e2e3df",
                "surface-tint": "#525f71",
                "on-secondary-fixed-variant": "#2f4865",
                "inverse-surface": "#2f312e",
                "on-surface": "#1a1c1a",
                "on-background": "#1a1c1a",
                "inverse-on-surface": "#f0f1ed",
                "surface-container-lowest": "#ffffff",
                "on-tertiary": "#ffffff",
                "surface-container-high": "#e8e8e4",
                "surface-container": "#edeeea",
                "outline": "#767683",
                "on-surface-variant": "#454652",
                "primary": "#0e1c2b",
                "primary-fixed": "#d6e4f9",
                "on-tertiary-fixed": "#261900",
                "tertiary-container": "#402c00",
                "secondary-fixed": "#d1e4ff",
                "surface-container-low": "#f3f4f0",
                "on-error-container": "#93000a",
                "surface": "#f9faf5"
            },
            fontFamily: {
                "headline": ["Noto Serif", "serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            },
        },
    },
    plugins: [],
}