import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const SUPPORTED_LANGUAGES = ['en', 'de', 'ru'];
const STORAGE_KEY = 'hotelcss-language';

export const UI_TRANSLATIONS = {
    en: {
        settings: 'Settings',
        logout: 'Logout',
        searchOperations: 'Search operations...',
        backToDashboard: 'Back to dashboard',
        administrator: 'Administrator',
        manager: 'Manager',
        reception: 'Reception',
        staff: 'Staff',
        housekeeping: 'Housekeeping',
        restaurant: 'Restaurant',
        room: 'Room',
        dashboard: 'Dashboard',
        adminSuite: 'ADMIN SUITE',
        hotelManagerSuite: 'HOTEL MANAGER SUITE',
        receptionSuite: 'RECEPTION SUITE',
        staffSuite: 'STAFF SUITE',
        roomSuite: 'ROOM SUITE',
    },
    de: {
        settings: 'Einstellungen',
        logout: 'Abmelden',
        searchOperations: 'Vorgaenge suchen...',
        backToDashboard: 'Zurueck zum Dashboard',
        administrator: 'Administrator',
        manager: 'Manager',
        reception: 'Rezeption',
        staff: 'Mitarbeiter',
        housekeeping: 'Housekeeping',
        restaurant: 'Restaurant',
        room: 'Zimmer',
        dashboard: 'Dashboard',
        adminSuite: 'ADMIN BEREICH',
        hotelManagerSuite: 'HOTELMANAGER BEREICH',
        receptionSuite: 'REZEPTION BEREICH',
        staffSuite: 'MITARBEITER BEREICH',
        roomSuite: 'ZIMMER BEREICH',
    },
    ru: {
        settings: 'Настройки',
        logout: 'Выйти',
        searchOperations: 'Поиск операций...',
        backToDashboard: 'Назад к панели',
        administrator: 'Администратор',
        manager: 'Менеджер',
        reception: 'Ресепшн',
        staff: 'Персонал',
        housekeeping: 'Хаускипинг',
        restaurant: 'Ресторан',
        room: 'Номер',
        dashboard: 'Панель',
        adminSuite: 'АДМИН ПАНЕЛЬ',
        hotelManagerSuite: 'ПАНЕЛЬ МЕНЕДЖЕРА ОТЕЛЯ',
        receptionSuite: 'ПАНЕЛЬ РЕСЕПШН',
        staffSuite: 'ПАНЕЛЬ ПЕРСОНАЛА',
        roomSuite: 'ПАНЕЛЬ НОМЕРА',
    },
};

export const PHRASE_TRANSLATIONS = {
    de: {
        'Operational Overview': 'Betriebsuebersicht',
        'Reception Overview': 'Rezeptionsuebersicht',
        'Room Overview': 'Zimmeruebersicht',
        'Admin Dashboard': 'Admin-Dashboard',
        'Manager Dashboard': 'Manager-Dashboard',
        'Reception Dashboard': 'Rezeptions-Dashboard',
        'Staff Dashboard': 'Mitarbeiter-Dashboard',
        'Room Dashboard': 'Zimmer-Dashboard',
        'Reception Requests': 'Rezeptionsanfragen',
        'Reception Rooms': 'Rezeptionszimmer',
        'Staff Requests': 'Mitarbeiteranfragen',
        'Room Rewards': 'Zimmerpraemien',
        'Room Vouchers': 'Zimmergutscheine',
        'Reception Actions': 'Rezeptionsaktionen',
        'Executive Actions': 'Leitungsaktionen',
        'My Tasks': 'Meine Aufgaben',
        'Service requests assigned to your department.': 'Serviceanfragen fuer Ihre Abteilung.',
        'No pending requests.': 'Keine offenen Anfragen.',
        'View All Requests': 'Alle Anfragen anzeigen',
        'Total Rooms': 'Zimmer gesamt',
        'Available Rooms': 'Verfuegbare Zimmer',
        'Total Requests': 'Anfragen gesamt',
        'Pending Requests': 'Offene Anfragen',
        'Room Information': 'Zimmerinformationen',
        'Create Service Request': 'Serviceanfrage erstellen',
        'Report an Issue': 'Problem melden',
        'Reception Request': 'Rezeptionsanfrage',
        'My Requests': 'Meine Anfragen',
        'Hotel Events': 'Hotelveranstaltungen',
        'Campaigns': 'Kampagnen',
        'Point Shop': 'Punkteshop',
        'My Reward Vouchers': 'Meine Praemiengutscheine',
        'Open': 'Oeffnen',
        'Live': 'Live',
        'Today': 'Heute',
        'Urgent': 'Dringend',
        'Available': 'Verfuegbar',
        'Quantity:': 'Menge:',
        'Note:': 'Notiz:',
        'Room': 'Zimmer',
        'Settings': 'Einstellungen',
        'Logout': 'Abmelden',
        'Requests': 'Anfragen',
        'Rooms': 'Zimmer',
        'Departments': 'Abteilungen',
        'Staff': 'Mitarbeiter',
        'Events': 'Veranstaltungen',
        'Vouchers': 'Gutscheine',
        'Reception Services': 'Rezeptionsdienste',
        'Room assistant': 'Zimmerassistent',
        'Open chat': 'Chat oeffnen',
        'Close chat': 'Chat schliessen',
        'Close': 'Schliessen',
        'Send': 'Senden',
        'Thinking...': 'Denke...',
        'Type your request...': 'Geben Sie Ihre Anfrage ein...',
        'Confirm': 'Bestaetigen',
        'Processing...': 'Verarbeite...',
        'Loading dashboard...': 'Dashboard wird geladen...',
        'Loading room dashboard...': 'Zimmer-Dashboard wird geladen...',
        'Loading reception services...': 'Rezeptionsdienste werden geladen...',
        'Loading hotel events...': 'Hotelveranstaltungen werden geladen...',
        'Create announcements, meal menus and bonus point campaigns for guests.': 'Erstellen Sie Ankuendigungen, Menues und Bonuspunkt-Kampagnen fuer Gaeste.',
        'Add Event': 'Ereignis hinzufuegen',
        'No hotel events defined yet.': 'Noch keine Hotelveranstaltungen vorhanden.',
        'Edit': 'Bearbeiten',
        'Delete': 'Loeschen',
        'Edit Event': 'Ereignis bearbeiten',
        'Create Event': 'Ereignis erstellen',
        'Title *': 'Titel *',
        'Description': 'Beschreibung',
        'Event Type': 'Ereignistyp',
        'Active': 'Aktiv',
        'Start Date/Time': 'Startdatum/-zeit',
        'End Date/Time': 'Enddatum/-zeit',
        'Extra Points': 'Extra Punkte',
        'Cancel': 'Abbrechen',
        'Update Event': 'Ereignis aktualisieren',
        'General': 'Allgemein',
        'Meal / Menu': 'Mahlzeit / Menue',
        'Bonus Point Campaign': 'Bonuspunkte-Kampagne',
        'Are you sure you want to delete the event': 'Sind Sie sicher, dass Sie das Ereignis loeschen moechten',
        'Click to toggle active status': 'Klicken, um den Status umzuschalten',
        'Inactive': 'Inaktiv',
        'Start:': 'Start:',
        'End:': 'Ende:',
        'Bonus point campaign is active for eligible purchases.': 'Bonuspunkte-Kampagne ist fuer berechtigte Einkaeufe aktiv.',
        'Reception services': 'Rezeptionsdienste',
        'Manage wake-up calls and pick-up times with the same editorial clarity as the guest-facing portal.': 'Verwalten Sie Weckrufe und Abholzeiten mit derselben Klarheit wie im Gastportal.',
        'No reception services found.': 'Keine Rezeptionsdienste gefunden.',
        'Hi! I am your digital concierge. I can order room service, set wake-up calls, check your points balance, or show you the point shop.': 'Hallo! Ich bin Ihr digitaler Concierge. Ich kann Zimmerservice bestellen, Weckrufe einrichten, Ihren Punktestand pruefen oder den Punkteshop zeigen.',
        'I am your Hotel Assistant. Please tell me what you need for your room.': 'Ich bin Ihr Hotelassistent. Bitte sagen Sie mir, was Sie fuer Ihr Zimmer brauchen.',
        'What time and date would you like me to set the wake-up call for?': 'Welche Uhrzeit und welches Datum soll ich fuer den Weckruf einstellen?',
        'At this time, we do not have any active promotional campaigns. Please check back later!': 'Derzeit gibt es keine aktiven Werbekampagnen. Bitte schauen Sie spaeter noch einmal vorbei!',
        'We do not have any special meal menus posted at the moment. Please check with the restaurant!': 'Derzeit sind keine speziellen Speisekarten verfuegbar. Bitte fragen Sie im Restaurant nach!',
        'Sorry, I couldn\'t understand that. Try something like "2 towels", "wake me up at 8 AM", or "what can I buy with points?".': 'Entschuldigung, das habe ich nicht verstanden. Versuchen Sie etwas wie "2 Handtuecher", "wecke mich um 8 Uhr" oder "was kann ich mit Punkten kaufen?".',
        'Order confirmed! Your request has been sent.': 'Bestellung bestaetigt! Ihre Anfrage wurde gesendet.',
        'Requested via AI Chatbot': 'Angefragt ueber KI-Chatbot',
        'Lütfen bir oda numarası girin.': 'Bitte geben Sie eine Zimmernummer ein.',
        'Lütfen pick-up için bir tarih ve saat seçin.': 'Bitte waehlen Sie ein Datum und eine Uhrzeit fuer die Abholung.',
        'Pick-up zamanı başarıyla kaydedildi veya güncellendi.': 'Abholzeit wurde erfolgreich gespeichert oder aktualisiert.',
        'Pick-up zamanı kaydedilirken bir hata oluştu.': 'Beim Speichern der Abholzeit ist ein Fehler aufgetreten.',
        'Bu kaydı silmek istediğinize emin misiniz?': 'Moechten Sie diesen Eintrag wirklich loeschen?',
        'Pick-up zamanı gir / güncelle': 'Abholzeit eingeben / aktualisieren',
        'Oda numarası girerek misafirler için yeni bir pick-up (transfer) saati tanımlayabilir veya mevcut zamanı güncelleyebilirsiniz.': 'Mit einer Zimmernummer koennen Sie eine neue Abholzeit (Transfer) fuer Gaeste festlegen oder eine bestehende Zeit aktualisieren.',
        'Örn: 101': 'z.B.: 101',
        'Örneğin: Havaalanı transferi, otelden 2 saat önce çıkış.': 'Beispiel: Flughafentransfer, Abfahrt 2 Stunden vor Verlassen des Hotels.',
        'Kaydediliyor...': 'Wird gespeichert...',
        'Pick-up zamanı kaydet': 'Abholzeit speichern',
        'Manage Staff': 'Mitarbeiter verwalten',
        'View, create, and manage staff members': 'Mitarbeiter anzeigen, erstellen und verwalten',
        'Open Roster': 'Mitarbeiterliste oeffnen',
        'Manage Departments': 'Abteilungen verwalten',
        'Configure hotel departments': 'Hotelabteilungen konfigurieren',
        'Configure Org': 'Organisation konfigurieren',
        'View Requests': 'Anfragen anzeigen',
        'Monitor and manage guest requests': 'Gaesteanfragen ueberwachen und verwalten',
        'Queue Board': 'Warteschlange',
        'Manage Rooms': 'Zimmer verwalten',
        'View and manage hotel rooms': 'Hotelzimmer anzeigen und verwalten',
        'Inventory': 'Bestand',
        'Create single or bulk rooms': 'Einzelne oder mehrere Zimmer erstellen',
        'Service Items': 'Serviceartikel',
        'Manage service items and menu': 'Serviceartikel und Menue verwalten',
        'Edit Catalog': 'Katalog bearbeiten',
        'Configure hotel events, meal info and earn points campaigns': 'Hotelveranstaltungen, Menueinformationen und Punktekampagnen konfigurieren',
        'Reward Vouchers': 'Praemiengutscheine',
        'View and manage guest reward vouchers and redemptions': 'Gaeste-Praemiengutscheine und Einloesungen verwalten',
        'Loyalty Suite': 'Loyalitaetsbereich',
        'Manage Surveys': 'Umfragen verwalten',
        'Create active feedback surveys for guests to intercept issues early.': 'Aktive Feedback-Umfragen fuer Gaeste erstellen, um Probleme frueh zu erkennen.',
        'Survey Creator': 'Umfrage-Editor',
        'Survey Results': 'Umfrageergebnisse',
        'Analyze guest feedback and view specific room responses.': 'Gaestefeedback analysieren und Antworten einzelner Zimmer ansehen.',
        'View Analytics': 'Analysen ansehen',
        'Guest Requests': 'Gaesteanfragen',
        'Filter, review, and update guest requests.': 'Gaesteanfragen filtern, pruefen und aktualisieren.',
        'All Status': 'Alle Status',
        'In Process': 'In Bearbeitung',
        'All Types': 'Alle Typen',
        'Search by room number, service item, or request ID...': 'Nach Zimmernummer, Serviceartikel oder Anfrage-ID suchen...',
        'No requests found': 'Keine Anfragen gefunden',
        'Type': 'Typ',
        'Photo': 'Foto',
        'Date': 'Datum',
        'Action': 'Aktion',
        'View': 'Ansehen',
        'No photo': 'Kein Foto',
        'Start': 'Starten',
        'Complete': 'Abschliessen',
        'Request': 'Anfrage',
        'Room Management': 'Zimmerverwaltung',
        'DASHBOARD': 'DASHBOARD',
        'CAMPAIGNS': 'KAMPAGNEN',
        'EVENTS': 'VERANSTALTUNGEN',
        'MY REQUESTS': 'MEINE ANFRAGEN',
        'POINT SHOP': 'PUNKTESHOP',
        'VOUCHERS': 'GUTSCHEINE',
        'ROOMS': 'ZIMMER',
        'ROOM': 'ZIMMER',
        'ROOM SUITE': 'ZIMMER BEREICH',
        'Manage room availability, occupancy, points, and check-outs.': 'Zimmerverfuegbarkeit, Belegung, Punkte und Check-outs verwalten.',
        'No rooms found': 'Keine Zimmer gefunden',
        'Current guest email': 'Aktuelle Gast-E-Mail',
        'Points': 'Punkte',
        '- Sub': '- Abzug',
        '+ Add': '+ Hinzufuegen',
        'Check-out room': 'Zimmer auschecken',
        'How many points would you like to add to Room': 'Wie viele Punkte moechten Sie Zimmer',
        'How many points would you like to SUBTRACT from Room': 'Wie viele Punkte moechten Sie von Zimmer',
        'Please enter a valid number greater than 0.': 'Bitte geben Sie eine gueltige Zahl groesser als 0 ein.',
        'Successfully added': 'Erfolgreich hinzugefuegt',
        'Successfully subtracted': 'Erfolgreich abgezogen',
        'Failed to add points to Room': 'Punkte konnten Zimmer nicht hinzugefuegt werden',
        'Failed to subtract points from Room': 'Punkte konnten von Zimmer nicht abgezogen werden',
        'Are you sure you want to check-out Room': 'Moechten Sie Zimmer wirklich auschecken',
        'This will finalize the stay, move data to history, clear all requests and reset the room.': 'Dadurch wird der Aufenthalt abgeschlossen, Daten in die Historie verschoben, alle Anfragen geloescht und das Zimmer zurueckgesetzt.',
        'Bu odayı "Available" yaparsan, odaya atanmış tüm bilgiler (konuk maili vb.) silinecek.\nDevam etmek istiyor musun?': 'Wenn Sie dieses Zimmer auf "Verfuegbar" setzen, werden alle zugewiesenen Informationen (z. B. Gaeste-E-Mail) geloescht.\nMoechten Sie fortfahren?',
        'Request room service or amenities.': 'Zimmerservice oder Ausstattungen anfordern.',
        'Report problems in your room.': 'Probleme in Ihrem Zimmer melden.',
        'Request wake-up calls or other reception services.': 'Weckrufe oder andere Rezeptionsdienste anfordern.',
        'View your request history.': 'Ihre Anfragehistorie anzeigen.',
        'See today\'s events, announcements and meal info.': 'Heutige Veranstaltungen, Ankuendigungen und Menueinformationen ansehen.',
        'View active bonus campaigns.': 'Aktive Bonuskampagnen anzeigen.',
        'Spend points on exclusive rewards.': 'Punkte fuer exklusive Praemien einloesen.',
        'View earned reward codes.': 'Erhaltene Praemiencodes anzeigen.',
        'This dashboard is for room-based access. Guests can scan QR codes to access room-specific features.': 'Dieses Dashboard ist fuer den zimmerbasierten Zugriff. Gaeste koennen QR-Codes scannen, um zimmerspezifische Funktionen zu nutzen.',
        'Jump into core reception modules.': 'Direkt zu den zentralen Rezeptionsmodulen springen.',
        'View and update room status.': 'Zimmerstatus anzeigen und aktualisieren.',
        'View and manage guest service requests.': 'Gaeste-Serviceanfragen anzeigen und verwalten.',
        'Open Services': 'Dienste oeffnen',
        'Failed to load requests': 'Anfragen konnten nicht geladen werden',
        'Failed to load rooms': 'Zimmer konnten nicht geladen werden',
        'Failed to load room information': 'Zimmerinformationen konnten nicht geladen werden',
        'Failed to load dashboard statistics': 'Dashboard-Statistiken konnten nicht geladen werden',
        'Failed to update request status': 'Anfragestatus konnte nicht aktualisiert werden',
        'Failed to delete request': 'Anfrage konnte nicht geloescht werden',
        'Request status updated successfully': 'Anfragestatus erfolgreich aktualisiert',
        'Request deleted successfully': 'Anfrage erfolgreich geloescht',
        'Room status updated successfully': 'Zimmerstatus erfolgreich aktualisiert',
        'Failed to update room status': 'Zimmerstatus konnte nicht aktualisiert werden',
        'Failed to check-out room': 'Zimmer konnte nicht ausgecheckt werden',
        'Application Settings': 'Anwendungseinstellungen',
        'Choose your preferred language for the application interface.': 'Wählen Sie Ihre bevorzugte Sprache für die Benutzeroberfläche.',
        'Language': 'Sprache',
        'Changes are applied immediately and saved for your next session.': 'Änderungen werden sofort angewendet und für die nächste Sitzung gespeichert.',
        'English': 'English',
        'Deutsch': 'Deutsch',
        'Русский': 'Russisch',
        'Event successfully activated!': 'Ereignis erfolgreich aktiviert!',
        'Event successfully deactivated!': 'Ereignis erfolgreich deaktiviert!',
        'Failed to toggle status': 'Status konnte nicht umgeschaltet werden',
        'Please add at least one bonus rule with Bonus Points > 0.': 'Bitte fügen Sie mindestens eine Bonusregel mit Bonuspunkten > 0 hinzu.',
        'Bonus point campaign event(s) created successfully': 'Bonuspunkte-Kampagnenereignis(se) erfolgreich erstellt',
        'Hotel event updated successfully': 'Hotelereignis erfolgreich aktualisiert',
        'Hotel event created successfully': 'Hotelereignis erfolgreich erstellt',
        'Failed to save hotel event': 'Hotelereignis konnte nicht gespeichert werden',
        'Hotel event deleted successfully': 'Hotelereignis erfolgreich gelöscht',
        'Failed to delete hotel event': 'Hotelereignis konnte nicht gelöscht werden',
        'Bonus rules (input array)': 'Bonusregeln (Eingabearray)',
        'Each rule becomes a separate BonusPoint event+campaign in backend.': 'Jede Regel wird im Backend als separates BonusPoint-Ereignis und Kampagne erstellt.',
        '+ Add rule': '+ Regel hinzufügen',
        'Campaign Type': 'Kampagnentyp',
        'All Items': 'Alle Artikel',
        'Specific Item': 'Bestimmter Artikel',
        'Service Item (SpecificItem)': 'Serviceartikel (SpecificItem)',
        'Select service item...': 'Serviceartikel auswählen...',
        'Remove': 'Entfernen',
        'Meal Info (breakfast / lunch / dinner details)': 'Mahlzeiteninfo (Frühstück / Mittagessen / Abendessen)',
        'e.g. Breakfast: ...\nLunch: ...\nDinner: ...': 'z.B. Frühstück: ...\nMittagessen: ...\nAbendessen: ...',
        'Daily Menus': 'Tagesmenues',
        'No active content is available right now.': 'Derzeit sind keine aktiven Inhalte verfügbar.',
        'There are no active bonus campaigns right now.': 'Derzeit gibt es keine aktiven Bonuskampagnen.',
        'Failed to load bonus campaigns': 'Bonuskampagnen konnten nicht geladen werden',
        'Campaign Dashboard': 'Kampagnen-Dashboard',
        'Active bonus campaigns for room users.': 'Aktive Bonuskampagnen für Zimmernutzer.',
    },
    ru: {
        'Operational Overview': 'Обзор операций',
        'Reception Overview': 'Обзор ресепшн',
        'Room Overview': 'Обзор номера',
        'Admin Dashboard': 'Панель администратора',
        'Manager Dashboard': 'Панель менеджера',
        'Reception Dashboard': 'Панель ресепшн',
        'Staff Dashboard': 'Панель персонала',
        'Room Dashboard': 'Панель номера',
        'Reception Requests': 'Запросы ресепшн',
        'Reception Rooms': 'Номера ресепшн',
        'Staff Requests': 'Запросы персонала',
        'Room Rewards': 'Награды номера',
        'Room Vouchers': 'Купоны номера',
        'Reception Actions': 'Действия ресепшн',
        'Executive Actions': 'Управленческие действия',
        'My Tasks': 'Мои задачи',
        'Service requests assigned to your department.': 'Сервисные запросы, назначенные вашему отделу.',
        'No pending requests.': 'Нет ожидающих запросов.',
        'View All Requests': 'Посмотреть все запросы',
        'Total Rooms': 'Всего номеров',
        'Available Rooms': 'Доступные номера',
        'Total Requests': 'Всего запросов',
        'Pending Requests': 'Ожидающие запросы',
        'Room Information': 'Информация о номере',
        'Create Service Request': 'Создать сервисный запрос',
        'Report an Issue': 'Сообщить о проблеме',
        'Reception Request': 'Запрос на ресепшн',
        'My Requests': 'Мои запросы',
        'Hotel Events': 'События отеля',
        'Campaigns': 'Кампании',
        'Point Shop': 'Магазин баллов',
        'My Reward Vouchers': 'Мои купоны наград',
        'Open': 'Открыть',
        'Live': 'Актуально',
        'Today': 'Сегодня',
        'Urgent': 'Срочно',
        'Available': 'Доступно',
        'Quantity:': 'Количество:',
        'Note:': 'Заметка:',
        'Room': 'Номер',
        'Settings': 'Настройки',
        'Logout': 'Выйти',
        'Requests': 'Запросы',
        'Rooms': 'Номера',
        'Departments': 'Отделы',
        'Staff': 'Персонал',
        'Events': 'События',
        'Vouchers': 'Купоны',
        'Reception Services': 'Услуги ресепшн',
        'Room assistant': 'Помощник номера',
        'Open chat': 'Открыть чат',
        'Close chat': 'Закрыть чат',
        'Close': 'Закрыть',
        'Send': 'Отправить',
        'Thinking...': 'Думаю...',
        'Type your request...': 'Введите ваш запрос...',
        'Confirm': 'Подтвердить',
        'Processing...': 'Обрабатывается...',
        'Loading dashboard...': 'Загрузка панели...',
        'Loading room dashboard...': 'Загрузка панели номера...',
        'Loading reception services...': 'Загрузка услуг ресепшн...',
        'Loading hotel events...': 'Загрузка событий отеля...',
        'Create announcements, meal menus and bonus point campaigns for guests.': 'Создавайте объявления, меню питания и кампании бонусных баллов для гостей.',
        'Add Event': 'Добавить событие',
        'No hotel events defined yet.': 'События отеля пока не добавлены.',
        'Edit': 'Изменить',
        'Delete': 'Удалить',
        'Edit Event': 'Изменить событие',
        'Create Event': 'Создать событие',
        'Title *': 'Заголовок *',
        'Description': 'Описание',
        'Event Type': 'Тип события',
        'Active': 'Активно',
        'Inactive': 'Неактивно',
        'Start Date/Time': 'Дата/время начала',
        'End Date/Time': 'Дата/время окончания',
        'Extra Points': 'Дополнительные баллы',
        'Cancel': 'Отмена',
        'Update Event': 'Обновить событие',
        'General': 'Общее',
        'Meal / Menu': 'Питание / Меню',
        'Bonus Point Campaign': 'Кампания бонусных баллов',
        'Click to toggle active status': 'Нажмите, чтобы переключить статус',
        'Start:': 'Начало:',
        'End:': 'Конец:',
        'Bonus point campaign is active for eligible purchases.': 'Кампания бонусных баллов активна для подходящих покупок.',
        'No reception services found.': 'Услуги ресепшн не найдены.',
        'Hi! I am your digital concierge. I can order room service, set wake-up calls, check your points balance, or show you the point shop.': 'Привет! Я ваш цифровой консьерж. Я могу заказать обслуживание в номер, установить будильник, проверить баланс баллов или показать магазин баллов.',
        'I am your Hotel Assistant. Please tell me what you need for your room.': 'Я ваш помощник отеля. Пожалуйста, скажите, что вам нужно для номера.',
        'What time and date would you like me to set the wake-up call for?': 'На какое время и дату установить звонок-будильник?',
        'At this time, we do not have any active promotional campaigns. Please check back later!': 'Сейчас у нас нет активных промо-кампаний. Пожалуйста, проверьте позже!',
        'We do not have any special meal menus posted at the moment. Please check with the restaurant!': 'Сейчас у нас нет специальных меню питания. Пожалуйста, уточните в ресторане!',
        'Sorry, I couldn\'t understand that. Try something like "2 towels", "wake me up at 8 AM", or "what can I buy with points?".': 'Извините, я не понял. Попробуйте, например: "2 полотенца", "разбуди меня в 8 утра" или "что можно купить за баллы?".',
        'Order confirmed! Your request has been sent.': 'Заказ подтвержден! Ваш запрос отправлен.',
        'Requested via AI Chatbot': 'Запрошено через ИИ-чатбот',
        'Lütfen bir oda numarası girin.': 'Пожалуйста, введите номер комнаты.',
        'Lütfen pick-up için bir tarih ve saat seçin.': 'Пожалуйста, выберите дату и время для трансфера.',
        'Pick-up zamanı başarıyla kaydedildi veya güncellendi.': 'Время трансфера успешно сохранено или обновлено.',
        'Pick-up zamanı kaydedilirken bir hata oluştu.': 'Произошла ошибка при сохранении времени трансфера.',
        'Bu kaydı silmek istediğinize emin misiniz?': 'Вы уверены, что хотите удалить эту запись?',
        'Pick-up zamanı gir / güncelle': 'Ввести / обновить время трансфера',
        'Oda numarası girerek misafirler için yeni bir pick-up (transfer) saati tanımlayabilir veya mevcut zamanı güncelleyebilirsiniz.': 'Введите номер комнаты, чтобы назначить новое время трансфера для гостей или обновить текущее.',
        'Örn: 101': 'Напр.: 101',
        'Örneğin: Havaalanı transferi, otelden 2 saat önce çıkış.': 'Например: трансфер в аэропорт, выезд за 2 часа до выхода из отеля.',
        'Kaydediliyor...': 'Сохранение...',
        'Pick-up zamanı kaydet': 'Сохранить время трансфера',
        'Manage Staff': 'Управление персоналом',
        'View, create, and manage staff members': 'Просмотр, создание и управление сотрудниками',
        'Open Roster': 'Открыть список',
        'Manage Departments': 'Управление отделами',
        'Configure hotel departments': 'Настройка отделов отеля',
        'Configure Org': 'Настроить структуру',
        'View Requests': 'Просмотр запросов',
        'Monitor and manage guest requests': 'Отслеживание и управление запросами гостей',
        'Queue Board': 'Очередь',
        'Manage Rooms': 'Управление номерами',
        'View and manage hotel rooms': 'Просмотр и управление номерами отеля',
        'Inventory': 'Инвентарь',
        'Create single or bulk rooms': 'Создание одного или нескольких номеров',
        'Service Items': 'Сервисные позиции',
        'Manage service items and menu': 'Управление сервисными позициями и меню',
        'Edit Catalog': 'Редактировать каталог',
        'Configure hotel events, meal info and earn points campaigns': 'Настройка событий отеля, меню и кампаний бонусных баллов',
        'Reward Vouchers': 'Наградные купоны',
        'View and manage guest reward vouchers and redemptions': 'Просмотр и управление купонами гостей и их погашением',
        'Loyalty Suite': 'Раздел лояльности',
        'Manage Surveys': 'Управление опросами',
        'Create active feedback surveys for guests to intercept issues early.': 'Создание активных опросов обратной связи для раннего выявления проблем.',
        'Survey Creator': 'Конструктор опросов',
        'Survey Results': 'Результаты опросов',
        'Analyze guest feedback and view specific room responses.': 'Анализ отзывов гостей и просмотр ответов по конкретным номерам.',
        'View Analytics': 'Открыть аналитику',
        'Guest Requests': 'Запросы гостей',
        'Filter, review, and update guest requests.': 'Фильтруйте, проверяйте и обновляйте запросы гостей.',
        'All Status': 'Все статусы',
        'In Process': 'В процессе',
        'All Types': 'Все типы',
        'Search by room number, service item, or request ID...': 'Поиск по номеру комнаты, сервису или ID запроса...',
        'No requests found': 'Запросы не найдены',
        'Type': 'Тип',
        'Photo': 'Фото',
        'Date': 'Дата',
        'Action': 'Действие',
        'View': 'Открыть',
        'No photo': 'Фото нет',
        'Start': 'Начать',
        'Complete': 'Завершить',
        'Request': 'Запрос',
        'Room Management': 'Управление номерами',
        'DASHBOARD': 'ПАНЕЛЬ',
        'CAMPAIGNS': 'КАМПАНИИ',
        'EVENTS': 'СОБЫТИЯ',
        'MY REQUESTS': 'МОИ ЗАПРОСЫ',
        'POINT SHOP': 'МАГАЗИН БАЛЛОВ',
        'VOUCHERS': 'КУПОНЫ',
        'ROOMS': 'НОМЕРА',
        'ROOM': 'НОМЕР',
        'ROOM SUITE': 'ПАНЕЛЬ НОМЕРА',
        'Manage room availability, occupancy, points, and check-outs.': 'Управление доступностью, занятостью, баллами и выездом из номеров.',
        'No rooms found': 'Номера не найдены',
        'Current guest email': 'Текущий email гостя',
        'Points': 'Баллы',
        '- Sub': '- Списать',
        '+ Add': '+ Добавить',
        'Check-out room': 'Оформить выезд',
        'How many points would you like to add to Room': 'Сколько баллов добавить в номер',
        'How many points would you like to SUBTRACT from Room': 'Сколько баллов списать из номера',
        'Please enter a valid number greater than 0.': 'Введите корректное число больше 0.',
        'Successfully added': 'Успешно добавлено',
        'Successfully subtracted': 'Успешно списано',
        'Failed to add points to Room': 'Не удалось добавить баллы в номер',
        'Failed to subtract points from Room': 'Не удалось списать баллы из номера',
        'Are you sure you want to check-out Room': 'Вы уверены, что хотите оформить выезд из номера',
        'This will finalize the stay, move data to history, clear all requests and reset the room.': 'Это завершит проживание, перенесет данные в историю, очистит запросы и сбросит номер.',
        'Bu odayı "Available" yaparsan, odaya atanmış tüm bilgiler (konuk maili vb.) silinecek.\nDevam etmek istiyor musun?': 'Если сделать комнату "Доступной", все назначенные данные (например, email гостя) будут удалены.\nПродолжить?',
        'Request room service or amenities.': 'Запросить обслуживание номера или удобства.',
        'Report problems in your room.': 'Сообщить о проблемах в номере.',
        'Request wake-up calls or other reception services.': 'Запросить звонок-будильник или другие услуги ресепшн.',
        'View your request history.': 'Просмотреть историю ваших запросов.',
        'See today\'s events, announcements and meal info.': 'Посмотреть события, объявления и информацию о питании на сегодня.',
        'View active bonus campaigns.': 'Просмотреть активные бонусные кампании.',
        'Spend points on exclusive rewards.': 'Потратить баллы на эксклюзивные награды.',
        'View earned reward codes.': 'Просмотреть полученные коды наград.',
        'This dashboard is for room-based access. Guests can scan QR codes to access room-specific features.': 'Эта панель предназначена для доступа из номера. Гости могут сканировать QR-коды для доступа к функциям номера.',
        'Jump into core reception modules.': 'Перейти к основным модулям ресепшн.',
        'View and update room status.': 'Просмотр и обновление статуса номера.',
        'View and manage guest service requests.': 'Просмотр и управление сервисными запросами гостей.',
        'Open Services': 'Открыть сервисы',
        'Failed to load requests': 'Не удалось загрузить запросы',
        'Failed to load rooms': 'Не удалось загрузить номера',
        'Failed to load room information': 'Не удалось загрузить информацию о номере',
        'Failed to load dashboard statistics': 'Не удалось загрузить статистику панели',
        'Failed to update request status': 'Не удалось обновить статус запроса',
        'Failed to delete request': 'Не удалось удалить запрос',
        'Request status updated successfully': 'Статус запроса успешно обновлен',
        'Request deleted successfully': 'Запрос успешно удален',
        'Room status updated successfully': 'Статус номера успешно обновлен',
        'Failed to update room status': 'Не удалось обновить статус номера',
        'Failed to check-out room': 'Не удалось оформить выезд',
        'Application Settings': 'Настройки приложения',
        'Choose your preferred language for the application interface.': 'Выберите предпочитаемый язык интерфейса приложения.',
        'Language': 'Язык',
        'Changes are applied immediately and saved for your next session.': 'Изменения применяются сразу и сохраняются для следующей сессии.',
        'English': 'English',
        'Deutsch': 'Deutsch',
        'Русский': 'Русский',
        'Event successfully activated!': 'Событие успешно активировано!',
        'Event successfully deactivated!': 'Событие успешно деактивировано!',
        'Failed to toggle status': 'Не удалось переключить статус',
        'Please add at least one bonus rule with Bonus Points > 0.': 'Добавьте хотя бы одно бонусное правило с Bonus Points > 0.',
        'Bonus point campaign event(s) created successfully': 'Событие(я) бонусной кампании успешно создано',
        'Hotel event updated successfully': 'Событие отеля успешно обновлено',
        'Hotel event created successfully': 'Событие отеля успешно создано',
        'Failed to save hotel event': 'Не удалось сохранить событие отеля',
        'Hotel event deleted successfully': 'Событие отеля успешно удалено',
        'Failed to delete hotel event': 'Не удалось удалить событие отеля',
        'Bonus rules (input array)': 'Бонусные правила (массив)',
        'Each rule becomes a separate BonusPoint event+campaign in backend.': 'Каждое правило создается как отдельное BonusPoint-событие и кампания в backend.',
        '+ Add rule': '+ Добавить правило',
        'Campaign Type': 'Тип кампании',
        'All Items': 'Все позиции',
        'Specific Item': 'Конкретная позиция',
        'Service Item (SpecificItem)': 'Сервисная позиция (SpecificItem)',
        'Select service item...': 'Выберите сервисную позицию...',
        'Remove': 'Удалить',
        'Meal Info (breakfast / lunch / dinner details)': 'Информация о питании (завтрак / обед / ужин)',
        'e.g. Breakfast: ...\nLunch: ...\nDinner: ...': 'например: Завтрак: ...\nОбед: ...\nУжин: ...',
        'Daily Menus': 'Ежедневное меню',
        'No active content is available right now.': 'Сейчас нет активного контента.',
        'There are no active bonus campaigns right now.': 'Сейчас нет активных бонусных кампаний.',
        'Failed to load bonus campaigns': 'Не удалось загрузить бонусные кампании',
        'Campaign Dashboard': 'Панель кампаний',
        'Active bonus campaigns for room users.': 'Активные бонусные кампании для пользователей номеров.',
    },
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
    const [language, setLanguageState] = useState('en');

    useEffect(() => {
        const storedLanguage = localStorage.getItem(STORAGE_KEY);
        if (storedLanguage && SUPPORTED_LANGUAGES.includes(storedLanguage)) {
            setLanguageState(storedLanguage);
        }
    }, []);

    const setLanguage = (nextLanguage) => {
        if (!SUPPORTED_LANGUAGES.includes(nextLanguage)) {
            return;
        }
        setLanguageState(nextLanguage);
        localStorage.setItem(STORAGE_KEY, nextLanguage);
    };

    const t = (key, fallback) => {
        const table = UI_TRANSLATIONS[language] || UI_TRANSLATIONS.en;
        return table[key] || fallback || key;
    };

    const translateUiText = (text) => {
        if (typeof text !== 'string') {
            return text;
        }
        const trimmed = text.trim();
        if (!trimmed || language === 'en') {
            return text;
        }
        const table = PHRASE_TRANSLATIONS[language] || {};
        if (table[trimmed]) {
            return text.replace(trimmed, table[trimmed]);
        }

        let translatedText = text;
        const keys = Object.keys(table).sort((a, b) => b.length - a.length);
        keys.forEach((key) => {
            if (translatedText.includes(key)) {
                translatedText = translatedText.split(key).join(table[key]);
            }
        });
        return translatedText;
    };

    const value = useMemo(
        () => ({
            language,
            setLanguage,
            supportedLanguages: SUPPORTED_LANGUAGES,
            t,
            translateUiText,
        }),
        [language],
    );

    return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within LanguageProvider');
    }
    return context;
};
