// <auto-generated />
using System;
using CSSHotel.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSSHotel.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260101150323_seedDatasToDb")]
    partial class seedDatasToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CSSHotel.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentName = "Housekeeping"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentName = "Kitchen"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentName = "Technic"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentName = "Reception"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentName = "Restaurant"
                        });
                });

            modelBuilder.Entity("CSSHotel.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<int>("ServiceItemId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoomNumber");

                    b.HasIndex("ServiceItemId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("CSSHotel.Models.Room", b =>
                {
                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QrCodeString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomNumber");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomNumber = 1101,
                            Floor = "1. Floor",
                            QrCodeString = "https://csshotel.com/login?room=1101"
                        },
                        new
                        {
                            RoomNumber = 1102,
                            Floor = "1. Floor",
                            QrCodeString = "https://csshotel.com/login?room=1102"
                        },
                        new
                        {
                            RoomNumber = 1103,
                            Floor = "1. Floor",
                            QrCodeString = "https://csshotel.com/login?room=1103"
                        },
                        new
                        {
                            RoomNumber = 1104,
                            Floor = "1. Floor",
                            QrCodeString = "https://csshotel.com/login?room=1104"
                        },
                        new
                        {
                            RoomNumber = 1105,
                            Floor = "1. Floor",
                            QrCodeString = "https://csshotel.com/login?room=1105"
                        },
                        new
                        {
                            RoomNumber = 1106,
                            Floor = "1. Floor",
                            QrCodeString = "https://csshotel.com/login?room=1106"
                        },
                        new
                        {
                            RoomNumber = 1107,
                            Floor = "1. Floor",
                            QrCodeString = "https://csshotel.com/login?room=1107"
                        },
                        new
                        {
                            RoomNumber = 1108,
                            Floor = "1. Floor",
                            QrCodeString = "https://csshotel.com/login?room=1108"
                        },
                        new
                        {
                            RoomNumber = 1109,
                            Floor = "1. Floor",
                            QrCodeString = "https://csshotel.com/login?room=1109"
                        },
                        new
                        {
                            RoomNumber = 1110,
                            Floor = "1. Floor",
                            QrCodeString = "https://csshotel.com/login?room=1110"
                        },
                        new
                        {
                            RoomNumber = 1111,
                            Floor = "1. Floor",
                            QrCodeString = "https://csshotel.com/login?room=1111"
                        },
                        new
                        {
                            RoomNumber = 1112,
                            Floor = "1. Floor",
                            QrCodeString = "https://csshotel.com/login?room=1112"
                        },
                        new
                        {
                            RoomNumber = 1113,
                            Floor = "1. Floor",
                            QrCodeString = "https://csshotel.com/login?room=1113"
                        },
                        new
                        {
                            RoomNumber = 1114,
                            Floor = "1. Floor",
                            QrCodeString = "https://csshotel.com/login?room=1114"
                        },
                        new
                        {
                            RoomNumber = 1115,
                            Floor = "1. Floor",
                            QrCodeString = "https://csshotel.com/login?room=1115"
                        },
                        new
                        {
                            RoomNumber = 1116,
                            Floor = "1. Floor",
                            QrCodeString = "https://csshotel.com/login?room=1116"
                        },
                        new
                        {
                            RoomNumber = 2201,
                            Floor = "2. Floor",
                            QrCodeString = "https://csshotel.com/login?room=2201"
                        },
                        new
                        {
                            RoomNumber = 2202,
                            Floor = "2. Floor",
                            QrCodeString = "https://csshotel.com/login?room=2202"
                        },
                        new
                        {
                            RoomNumber = 2203,
                            Floor = "2. Floor",
                            QrCodeString = "https://csshotel.com/login?room=2203"
                        },
                        new
                        {
                            RoomNumber = 2204,
                            Floor = "2. Floor",
                            QrCodeString = "https://csshotel.com/login?room=2204"
                        },
                        new
                        {
                            RoomNumber = 2205,
                            Floor = "2. Floor",
                            QrCodeString = "https://csshotel.com/login?room=2205"
                        },
                        new
                        {
                            RoomNumber = 2206,
                            Floor = "2. Floor",
                            QrCodeString = "https://csshotel.com/login?room=2206"
                        },
                        new
                        {
                            RoomNumber = 2207,
                            Floor = "2. Floor",
                            QrCodeString = "https://csshotel.com/login?room=2207"
                        },
                        new
                        {
                            RoomNumber = 2208,
                            Floor = "2. Floor",
                            QrCodeString = "https://csshotel.com/login?room=2208"
                        },
                        new
                        {
                            RoomNumber = 2209,
                            Floor = "2. Floor",
                            QrCodeString = "https://csshotel.com/login?room=2209"
                        },
                        new
                        {
                            RoomNumber = 2210,
                            Floor = "2. Floor",
                            QrCodeString = "https://csshotel.com/login?room=2210"
                        },
                        new
                        {
                            RoomNumber = 2211,
                            Floor = "2. Floor",
                            QrCodeString = "https://csshotel.com/login?room=2211"
                        },
                        new
                        {
                            RoomNumber = 2212,
                            Floor = "2. Floor",
                            QrCodeString = "https://csshotel.com/login?room=2212"
                        },
                        new
                        {
                            RoomNumber = 2213,
                            Floor = "2. Floor",
                            QrCodeString = "https://csshotel.com/login?room=2213"
                        },
                        new
                        {
                            RoomNumber = 2214,
                            Floor = "2. Floor",
                            QrCodeString = "https://csshotel.com/login?room=2214"
                        },
                        new
                        {
                            RoomNumber = 2215,
                            Floor = "2. Floor",
                            QrCodeString = "https://csshotel.com/login?room=2215"
                        },
                        new
                        {
                            RoomNumber = 2216,
                            Floor = "2. Floor",
                            QrCodeString = "https://csshotel.com/login?room=2216"
                        },
                        new
                        {
                            RoomNumber = 3301,
                            Floor = "3. Floor",
                            QrCodeString = "https://csshotel.com/login?room=3301"
                        },
                        new
                        {
                            RoomNumber = 3302,
                            Floor = "3. Floor",
                            QrCodeString = "https://csshotel.com/login?room=3302"
                        },
                        new
                        {
                            RoomNumber = 3303,
                            Floor = "3. Floor",
                            QrCodeString = "https://csshotel.com/login?room=3303"
                        },
                        new
                        {
                            RoomNumber = 3304,
                            Floor = "3. Floor",
                            QrCodeString = "https://csshotel.com/login?room=3304"
                        },
                        new
                        {
                            RoomNumber = 3305,
                            Floor = "3. Floor",
                            QrCodeString = "https://csshotel.com/login?room=3305"
                        },
                        new
                        {
                            RoomNumber = 3306,
                            Floor = "3. Floor",
                            QrCodeString = "https://csshotel.com/login?room=3306"
                        },
                        new
                        {
                            RoomNumber = 3307,
                            Floor = "3. Floor",
                            QrCodeString = "https://csshotel.com/login?room=3307"
                        },
                        new
                        {
                            RoomNumber = 3308,
                            Floor = "3. Floor",
                            QrCodeString = "https://csshotel.com/login?room=3308"
                        },
                        new
                        {
                            RoomNumber = 3309,
                            Floor = "3. Floor",
                            QrCodeString = "https://csshotel.com/login?room=3309"
                        },
                        new
                        {
                            RoomNumber = 3310,
                            Floor = "3. Floor",
                            QrCodeString = "https://csshotel.com/login?room=3310"
                        },
                        new
                        {
                            RoomNumber = 3311,
                            Floor = "3. Floor",
                            QrCodeString = "https://csshotel.com/login?room=3311"
                        },
                        new
                        {
                            RoomNumber = 3312,
                            Floor = "3. Floor",
                            QrCodeString = "https://csshotel.com/login?room=3312"
                        },
                        new
                        {
                            RoomNumber = 3313,
                            Floor = "3. Floor",
                            QrCodeString = "https://csshotel.com/login?room=3313"
                        },
                        new
                        {
                            RoomNumber = 3314,
                            Floor = "3. Floor",
                            QrCodeString = "https://csshotel.com/login?room=3314"
                        },
                        new
                        {
                            RoomNumber = 3315,
                            Floor = "3. Floor",
                            QrCodeString = "https://csshotel.com/login?room=3315"
                        },
                        new
                        {
                            RoomNumber = 3316,
                            Floor = "3. Floor",
                            QrCodeString = "https://csshotel.com/login?room=3316"
                        },
                        new
                        {
                            RoomNumber = 4401,
                            Floor = "4. Floor",
                            QrCodeString = "https://csshotel.com/login?room=4401"
                        },
                        new
                        {
                            RoomNumber = 4402,
                            Floor = "4. Floor",
                            QrCodeString = "https://csshotel.com/login?room=4402"
                        },
                        new
                        {
                            RoomNumber = 4403,
                            Floor = "4. Floor",
                            QrCodeString = "https://csshotel.com/login?room=4403"
                        },
                        new
                        {
                            RoomNumber = 4404,
                            Floor = "4. Floor",
                            QrCodeString = "https://csshotel.com/login?room=4404"
                        },
                        new
                        {
                            RoomNumber = 4405,
                            Floor = "4. Floor",
                            QrCodeString = "https://csshotel.com/login?room=4405"
                        },
                        new
                        {
                            RoomNumber = 4406,
                            Floor = "4. Floor",
                            QrCodeString = "https://csshotel.com/login?room=4406"
                        },
                        new
                        {
                            RoomNumber = 4407,
                            Floor = "4. Floor",
                            QrCodeString = "https://csshotel.com/login?room=4407"
                        },
                        new
                        {
                            RoomNumber = 4408,
                            Floor = "4. Floor",
                            QrCodeString = "https://csshotel.com/login?room=4408"
                        },
                        new
                        {
                            RoomNumber = 4409,
                            Floor = "4. Floor",
                            QrCodeString = "https://csshotel.com/login?room=4409"
                        },
                        new
                        {
                            RoomNumber = 4410,
                            Floor = "4. Floor",
                            QrCodeString = "https://csshotel.com/login?room=4410"
                        },
                        new
                        {
                            RoomNumber = 4411,
                            Floor = "4. Floor",
                            QrCodeString = "https://csshotel.com/login?room=4411"
                        },
                        new
                        {
                            RoomNumber = 4412,
                            Floor = "4. Floor",
                            QrCodeString = "https://csshotel.com/login?room=4412"
                        },
                        new
                        {
                            RoomNumber = 4413,
                            Floor = "4. Floor",
                            QrCodeString = "https://csshotel.com/login?room=4413"
                        },
                        new
                        {
                            RoomNumber = 4414,
                            Floor = "4. Floor",
                            QrCodeString = "https://csshotel.com/login?room=4414"
                        },
                        new
                        {
                            RoomNumber = 4415,
                            Floor = "4. Floor",
                            QrCodeString = "https://csshotel.com/login?room=4415"
                        },
                        new
                        {
                            RoomNumber = 4416,
                            Floor = "4. Floor",
                            QrCodeString = "https://csshotel.com/login?room=4416"
                        },
                        new
                        {
                            RoomNumber = 5501,
                            Floor = "5. Floor",
                            QrCodeString = "https://csshotel.com/login?room=5501"
                        },
                        new
                        {
                            RoomNumber = 5502,
                            Floor = "5. Floor",
                            QrCodeString = "https://csshotel.com/login?room=5502"
                        },
                        new
                        {
                            RoomNumber = 5503,
                            Floor = "5. Floor",
                            QrCodeString = "https://csshotel.com/login?room=5503"
                        },
                        new
                        {
                            RoomNumber = 5504,
                            Floor = "5. Floor",
                            QrCodeString = "https://csshotel.com/login?room=5504"
                        },
                        new
                        {
                            RoomNumber = 5505,
                            Floor = "5. Floor",
                            QrCodeString = "https://csshotel.com/login?room=5505"
                        },
                        new
                        {
                            RoomNumber = 5506,
                            Floor = "5. Floor",
                            QrCodeString = "https://csshotel.com/login?room=5506"
                        },
                        new
                        {
                            RoomNumber = 5507,
                            Floor = "5. Floor",
                            QrCodeString = "https://csshotel.com/login?room=5507"
                        },
                        new
                        {
                            RoomNumber = 5508,
                            Floor = "5. Floor",
                            QrCodeString = "https://csshotel.com/login?room=5508"
                        },
                        new
                        {
                            RoomNumber = 5509,
                            Floor = "5. Floor",
                            QrCodeString = "https://csshotel.com/login?room=5509"
                        },
                        new
                        {
                            RoomNumber = 5510,
                            Floor = "5. Floor",
                            QrCodeString = "https://csshotel.com/login?room=5510"
                        },
                        new
                        {
                            RoomNumber = 5511,
                            Floor = "5. Floor",
                            QrCodeString = "https://csshotel.com/login?room=5511"
                        },
                        new
                        {
                            RoomNumber = 5512,
                            Floor = "5. Floor",
                            QrCodeString = "https://csshotel.com/login?room=5512"
                        },
                        new
                        {
                            RoomNumber = 5513,
                            Floor = "5. Floor",
                            QrCodeString = "https://csshotel.com/login?room=5513"
                        },
                        new
                        {
                            RoomNumber = 5514,
                            Floor = "5. Floor",
                            QrCodeString = "https://csshotel.com/login?room=5514"
                        },
                        new
                        {
                            RoomNumber = 5515,
                            Floor = "5. Floor",
                            QrCodeString = "https://csshotel.com/login?room=5515"
                        },
                        new
                        {
                            RoomNumber = 5516,
                            Floor = "5. Floor",
                            QrCodeString = "https://csshotel.com/login?room=5516"
                        });
                });

            modelBuilder.Entity("CSSHotel.Models.ServiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("ServiceItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Name = "Towel"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Name = "Shampoo"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Name = "Extra Blanket"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            Name = "Hamburger"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            Name = "Cola"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            Name = "Fix AC"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            Name = "TV Remote"
                        });
                });

            modelBuilder.Entity("CSSHotel.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CSSHotel.Models.Request", b =>
                {
                    b.HasOne("CSSHotel.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSSHotel.Models.ServiceItem", "ServiceItem")
                        .WithMany()
                        .HasForeignKey("ServiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("ServiceItem");
                });

            modelBuilder.Entity("CSSHotel.Models.ServiceItem", b =>
                {
                    b.HasOne("CSSHotel.Models.Department", "Department")
                        .WithMany("ServiceItems")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CSSHotel.Models.Staff", b =>
                {
                    b.HasOne("CSSHotel.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CSSHotel.Models.Department", b =>
                {
                    b.Navigation("ServiceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
