// <auto-generated />
using System;
using CSSHotel.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSSHotel.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260106194654_AddRoomModelToDatabase")]
    partial class AddRoomModelToDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CSSHotel.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentName = "Housekeeping"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentName = "Kitchen"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentName = "Technic"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentName = "Reception"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentName = "Restaurant"
                        });
                });

            modelBuilder.Entity("CSSHotel.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<int>("ServiceItemId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoomNumber");

                    b.HasIndex("ServiceItemId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("CSSHotel.Models.Room", b =>
                {
                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<string>("QrCodeString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomNumber");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomNumber = 1101,
                            QrCodeString = "https://csshotel.com/login?room=1101",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 1102,
                            QrCodeString = "https://csshotel.com/login?room=1102",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 1103,
                            QrCodeString = "https://csshotel.com/login?room=1103",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 1104,
                            QrCodeString = "https://csshotel.com/login?room=1104",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 1105,
                            QrCodeString = "https://csshotel.com/login?room=1105",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 1106,
                            QrCodeString = "https://csshotel.com/login?room=1106",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 1107,
                            QrCodeString = "https://csshotel.com/login?room=1107",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 1108,
                            QrCodeString = "https://csshotel.com/login?room=1108",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 1109,
                            QrCodeString = "https://csshotel.com/login?room=1109",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 1110,
                            QrCodeString = "https://csshotel.com/login?room=1110",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 1111,
                            QrCodeString = "https://csshotel.com/login?room=1111",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 1112,
                            QrCodeString = "https://csshotel.com/login?room=1112",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 1113,
                            QrCodeString = "https://csshotel.com/login?room=1113",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 1114,
                            QrCodeString = "https://csshotel.com/login?room=1114",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 1115,
                            QrCodeString = "https://csshotel.com/login?room=1115",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 1116,
                            QrCodeString = "https://csshotel.com/login?room=1116",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 2201,
                            QrCodeString = "https://csshotel.com/login?room=2201",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 2202,
                            QrCodeString = "https://csshotel.com/login?room=2202",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 2203,
                            QrCodeString = "https://csshotel.com/login?room=2203",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 2204,
                            QrCodeString = "https://csshotel.com/login?room=2204",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 2205,
                            QrCodeString = "https://csshotel.com/login?room=2205",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 2206,
                            QrCodeString = "https://csshotel.com/login?room=2206",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 2207,
                            QrCodeString = "https://csshotel.com/login?room=2207",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 2208,
                            QrCodeString = "https://csshotel.com/login?room=2208",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 2209,
                            QrCodeString = "https://csshotel.com/login?room=2209",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 2210,
                            QrCodeString = "https://csshotel.com/login?room=2210",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 2211,
                            QrCodeString = "https://csshotel.com/login?room=2211",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 2212,
                            QrCodeString = "https://csshotel.com/login?room=2212",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 2213,
                            QrCodeString = "https://csshotel.com/login?room=2213",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 2214,
                            QrCodeString = "https://csshotel.com/login?room=2214",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 2215,
                            QrCodeString = "https://csshotel.com/login?room=2215",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 2216,
                            QrCodeString = "https://csshotel.com/login?room=2216",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 3301,
                            QrCodeString = "https://csshotel.com/login?room=3301",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 3302,
                            QrCodeString = "https://csshotel.com/login?room=3302",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 3303,
                            QrCodeString = "https://csshotel.com/login?room=3303",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 3304,
                            QrCodeString = "https://csshotel.com/login?room=3304",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 3305,
                            QrCodeString = "https://csshotel.com/login?room=3305",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 3306,
                            QrCodeString = "https://csshotel.com/login?room=3306",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 3307,
                            QrCodeString = "https://csshotel.com/login?room=3307",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 3308,
                            QrCodeString = "https://csshotel.com/login?room=3308",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 3309,
                            QrCodeString = "https://csshotel.com/login?room=3309",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 3310,
                            QrCodeString = "https://csshotel.com/login?room=3310",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 3311,
                            QrCodeString = "https://csshotel.com/login?room=3311",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 3312,
                            QrCodeString = "https://csshotel.com/login?room=3312",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 3313,
                            QrCodeString = "https://csshotel.com/login?room=3313",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 3314,
                            QrCodeString = "https://csshotel.com/login?room=3314",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 3315,
                            QrCodeString = "https://csshotel.com/login?room=3315",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 3316,
                            QrCodeString = "https://csshotel.com/login?room=3316",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 4401,
                            QrCodeString = "https://csshotel.com/login?room=4401",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 4402,
                            QrCodeString = "https://csshotel.com/login?room=4402",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 4403,
                            QrCodeString = "https://csshotel.com/login?room=4403",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 4404,
                            QrCodeString = "https://csshotel.com/login?room=4404",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 4405,
                            QrCodeString = "https://csshotel.com/login?room=4405",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 4406,
                            QrCodeString = "https://csshotel.com/login?room=4406",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 4407,
                            QrCodeString = "https://csshotel.com/login?room=4407",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 4408,
                            QrCodeString = "https://csshotel.com/login?room=4408",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 4409,
                            QrCodeString = "https://csshotel.com/login?room=4409",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 4410,
                            QrCodeString = "https://csshotel.com/login?room=4410",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 4411,
                            QrCodeString = "https://csshotel.com/login?room=4411",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 4412,
                            QrCodeString = "https://csshotel.com/login?room=4412",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 4413,
                            QrCodeString = "https://csshotel.com/login?room=4413",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 4414,
                            QrCodeString = "https://csshotel.com/login?room=4414",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 4415,
                            QrCodeString = "https://csshotel.com/login?room=4415",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 4416,
                            QrCodeString = "https://csshotel.com/login?room=4416",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 5501,
                            QrCodeString = "https://csshotel.com/login?room=5501",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 5502,
                            QrCodeString = "https://csshotel.com/login?room=5502",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 5503,
                            QrCodeString = "https://csshotel.com/login?room=5503",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 5504,
                            QrCodeString = "https://csshotel.com/login?room=5504",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 5505,
                            QrCodeString = "https://csshotel.com/login?room=5505",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 5506,
                            QrCodeString = "https://csshotel.com/login?room=5506",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 5507,
                            QrCodeString = "https://csshotel.com/login?room=5507",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 5508,
                            QrCodeString = "https://csshotel.com/login?room=5508",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 5509,
                            QrCodeString = "https://csshotel.com/login?room=5509",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 5510,
                            QrCodeString = "https://csshotel.com/login?room=5510",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 5511,
                            QrCodeString = "https://csshotel.com/login?room=5511",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 5512,
                            QrCodeString = "https://csshotel.com/login?room=5512",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 5513,
                            QrCodeString = "https://csshotel.com/login?room=5513",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 5514,
                            QrCodeString = "https://csshotel.com/login?room=5514",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 5515,
                            QrCodeString = "https://csshotel.com/login?room=5515",
                            Status = "Available"
                        },
                        new
                        {
                            RoomNumber = 5516,
                            QrCodeString = "https://csshotel.com/login?room=5516",
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("CSSHotel.Models.ServiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("ServiceItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            IsAvailable = true,
                            Name = "Towel",
                            Price = 0m
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            IsAvailable = true,
                            Name = "Shampoo",
                            Price = 0m
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            IsAvailable = true,
                            Name = "Extra Blanket",
                            Price = 0m
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            IsAvailable = true,
                            Name = "Hamburger",
                            Price = 0m
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            IsAvailable = true,
                            Name = "Cola",
                            Price = 0m
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            IsAvailable = true,
                            Name = "Fix AC",
                            Price = 0m
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            IsAvailable = true,
                            Name = "TV Remote",
                            Price = 0m
                        });
                });

            modelBuilder.Entity("CSSHotel.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CSSHotel.Models.Request", b =>
                {
                    b.HasOne("CSSHotel.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSSHotel.Models.ServiceItem", "ServiceItem")
                        .WithMany()
                        .HasForeignKey("ServiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("ServiceItem");
                });

            modelBuilder.Entity("CSSHotel.Models.ServiceItem", b =>
                {
                    b.HasOne("CSSHotel.Models.Department", "Department")
                        .WithMany("ServiceItems")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CSSHotel.Models.Staff", b =>
                {
                    b.HasOne("CSSHotel.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CSSHotel.Models.Department", b =>
                {
                    b.Navigation("ServiceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
